services:
  poke-db:
    build:
      context: .
      dockerfile: ./docker/database.Dockerfile
    image: poke-db:latest
    container_name: poke-db
    ports:
      - "5000:5000"
    volumes:
      - ./db_server/database:/app/database
    networks:
      - pokeNetwork
    develop:
      watch:
        - path: ./db_server
          action: rebuild
          ignore:
            - ./database
        - path: ./docker/database.Dockerfile
          action: rebuild
  poke-server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    image: poke-server:latest
    container_name: poke-server
    ports:
      - "80:80"
    networks:
      - pokeNetwork
    depends_on:
      - poke-db
    develop:
      watch:
        - path: ./fast_server
          action: rebuild
        - path: ./docker/server.Dockerfile
          action: rebuild

networks:
  pokeNetwork:
    driver: bridge