version: "3.3"
services:
    app-backend:
        build: ./server.Dockerfile
        image: app_backend
        container_name: backend
        restart: always
        ports:
            - 5000:5000
    app-frontend:
        build: ./ui.Dockerfile
        image: pokemaster
        container_name: frontend
        restart: always
        ports:
            - 4200:4200
        expose:
            - "4200"